# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notification_users', to='api.UserIntermediate'),
        ),
    ]
