# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
